### PR TITLE
introduce sticky class and style for figure caption

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by rettinghaus** [comment]
The corresponding PR in https://github.com/music-encoding/guidelines/pull/112 has been merged already. @kepper?

**Comment by rettinghaus** [comment]
addresses https://github.com/music-encoding/guidelines/issues/154
@bwbohl have a look and merge.

**Comment by kepper** [comment]
but we should keep 8d5aa0fd6e9ed24766e3822270c565149c94755f, shouldn't we?

**Comment by rettinghaus** [comment]
@kepper thanks for reminding me! now as 9abaa2f included in #126

**Pull request closed without merging**
