### PR TITLE
added recurring pedagogical events

### PR DESCRIPTION
**Pull request by annakijas1**
We would like to include a list of events that occur annually and include music encoding pedagogy on this page.

### CODE REVIEW

**Comment by annakijas1** [comment]
@musicEnfanthen can you check the bibbase script to make sure it will render properly for the events list? Thank you.

**Comment by musicEnfanthen** [comment]
@annakijas1 Thank you. Seems to render fine:
bibbase

Maybe you want to add a `&group0=type` to the end of the link src, so the "heading" `undefined` would be (at least) replaced by `misc`:

misc

It is possible that there are options to "rename" the types via CSS: https://bibbase.org/documentation

So something like: 

```
#[ID-OF-DIV-CONTAINER] #group_misc div.bibbase_group i+span { display: none; }
#[ID-OF-DIV-CONTAINER] #group_misc div.bibbase_group i:after { content: " Recurring events" }

```

**Comment by annakijas1** [comment]
@musicEnfanthen I made the update so it will use the misc heading. That's fine for now. Thanks!

**Comment by musicEnfanthen** [comment]
Looks good, thanks, @annakijas1 .

**Comment by annakijas1** [comment]
@musicEnfanthen Is there a way to adjust the "group by" filter function so it filters by one section at a time? Right now if you select "group by" keyword under "Recurring Events" if regroups everything from both the "Recurring Events" and "Selected Bibliography" sections.

**Comment by musicEnfanthen** [comment]
Hmm, seems to be a longer standing issue (with no priority) for bibbase: https://bibbase.userecho.com/de/communities/1/topics/136-two-bibbase-embedded-at-the-same-page

**Comment by annakijas1** [comment]
@musicEnfanthen That's too bad. I can always create a regular list and not use bibbase for the events.

**Comment by musicEnfanthen** [comment]
Yes, unfortunately there seems to be no support for multiple bibbase files on the same page yet. Creating a regular list sounds like a good workaround if you don't want to add a separate page solely for the events.

**Comment by annakijas1** [comment]
I'll change it to a regular list.

**Pull request merged**
