### PR TITLE
Add link checker GH action

### PR DESCRIPTION
**Pull request by musicEnfanthen**
This PR adds a GH action, which checks for broken links on a scheduled basis (every Sunday). The action auto-creates an issue if broken links were found. The action can also be triggered manually.

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
This action supports the great work done by @doerners in #188 and #189, so that in future broken links will no longer have to be detected manually.

**Comment by doerners** [comment]
Thanks a lot @musicEnfanthen!!! Great work.

One quick question though. Since there are still some not-yet-fixed broken links listed in #189, won't new issues be opened (that basically address the same problem), if the gh actions runs regularly on sundays, until those links are fixed?

**Comment by rettinghaus** [comment]
I was thinking the same. We should resolve #189 as soon as possible, before having hundreds of duplicates of this issue.

**Comment by musicEnfanthen** [comment]
Yes, I agree (see #189). Although I doubt that we would ever get to "hundreds of duplicates" ;)

**Comment by bwbohl** [comment]
Do I understand correctly, that this PR is blocked by #189 ?

**Comment by doerners** [comment]
Most of the broken links mentioned in #189 are fixed now but not all. So if @musicEnfanthen initiates the GH action it will find some links that throw a 404, especially some that originate from one of the "unused" folders. Not sure if this means that this PR should be blocked per se.

**Comment by musicEnfanthen** [comment]
Results of the latest link check (2 days ago) can be found here: https://github.com/musicEnfanthen/link-check-test/runs/1716916127?check_suite_focus=true

**Comment by musicEnfanthen** [comment]
Broken links are mostly in the unused or archive (old schemata) folder. Will try to provide some more fixes.

**Comment by musicEnfanthen** [comment]
We also should think about a way to obfuscate mail addresses: #200

**Comment by bwbohl** [comment]
concerning the old schemata linked from the archive page… the files are not in the website repo but in the schema repo. The links actually (as of today) do work when clicked manually. I think they fail because the link checker applies the markdown link check here, maybe the website link check would work?
As of the errors concerning weber-gesamtausgabe, they failed two days ago due to a hardware failure at the hosting enterprise…

Moreover, is there a way to exclude certain directories ('unused') from the check, that would be perfect. The rest is just some mailto links and one to an old conference website. Just submitted #201 for those.

**Comment by musicEnfanthen** [comment]
Thanks for #201 and the fixes. There is a way to exclude (or even replace) directions in the checker via the config file: https://github.com/musicEnfanthen/link-check-test/blob/main/.github/link-checker-config.json

**Comment by musicEnfanthen** [comment]
Will have a look

**Comment by musicEnfanthen** [comment]
Ok, got out all the outstanding broken links. There are still two minor issues with the markdown checker not ignoring the issue-template (and throwing 404), and the website checker detecting twitter link as broken although it is working. Opened issue reports in the corresponding repos.

**Comment by bwbohl** [comment]
guess that would render this PR mergeable?

**Comment by kepper** [comment]
this seems to be ready in general, but there is an issue with the tools upstream that would create an issue once per week about an incorrect link that is unrelated to us. We'll push this one month and see if there's progress upstream.

**Comment by musicEnfanthen** [comment]
Managed to fix the issue with the template, so the workflow is running through: https://github.com/musicEnfanthen/link-check-test/runs/2317949680?check_suite_focus=true

Additionally, I restricted the scheduled workflow jobs to only run on the main repo, not on forks.

So, this one is ready for review @bwbohl .

**Comment by bwbohl** [comment]
markdown link checker warnings:
```bash
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

**Comment by bwbohl** [comment]
Issue was created successfully created https://github.com/music-encoding/music-encoding.github.io/issues/219, but how do I see the broken links in https://github.com/music-encoding/music-encoding.github.io/actions/runs/740550819?

**Comment by bwbohl** [comment]
If I understand the report, no broken links are discovered, nevertheless "Check markdown links" fails

**Comment by musicEnfanthen** [comment]
The broken link is here: https://github.com/music-encoding/music-encoding.github.io/runs/2322236098?check_suite_focus=true#step:5:230

http://www.weber-gesamtausgabe.de seems to be down?

**Comment by musicEnfanthen** [comment]
At least we know the action works as expected ;)

**Comment by bwbohl** [comment]
It works perfectly! WeGa unfortunately is temporarily down…

**Comment by musicEnfanthen** [comment]
Thanks for the merge!

**Pull request merged**
