### PR TITLE
Add link to PDF

### PR DESCRIPTION
**Pull request by musicEnfanthen**
This PR adds a link to the PDF to the MEI Namespace and Schemas page (PDFs from previous versions are available from there, too).

### CODE REVIEW

**Review by rettinghaus — APPROVED** [review]
Great, thank you!

**Comment by rettinghaus** [comment]
On second thought, as this section has "Schemas" in the header, maybe move it to the end here?

**Comment by musicEnfanthen** [comment]
Thanks. Yes, already thought about this as well. On the other hand, all the previous versions have the PDF in the first place.... What do you think?

**Comment by rettinghaus** [comment]
I don't care too much. Let @ahankinson or @bwbohl decide?

**Comment by bwbohl** [comment]
I think it's misleading to out it in the Schemas section, but why not just rename the section to MEI 5.0?

Aside of that I'd prefer optimizing the contents by consuming releases and/or the schema and guidelines repos

**Comment by musicEnfanthen** [comment]
I'd propose to find a 'quick and easy' solution for now to somewhere deposit the PDF link, and do the content optimization in another step?

**Comment by rettinghaus** [comment]
Let's discuss this in the next ODD meeting.

**Pull request merged**
