### PR TITLE
add project page for BAZ

### PR DESCRIPTION
**Pull request by annakijas1**
Created project page for Bernd Alois Zimmermann Complete Edition. Cleanup of projects on the wiki.

### CODE REVIEW

**Review by rettinghaus — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
Thank you both for the additon of the BAZ project.

@bwbohl Could you please have a look at the project's members and update if needed?

**Comment by bwbohl** [comment]
The contributors list is not complete and depending on the goals not up to date. Should all project contributors be listed also past employees.

Also I'm not sure about the correct english terminology of the individual contributors; research associate vs. assistant and what about undergraduate or student assistants?

The text seems to be a translation of a text from the project website, which is copyrighted. The image is copyrighted, too…

I will check on this with the project lead.

**Comment by bwbohl** [comment]
Sidenote: would prefer to rename page to baz-ga instead of baz as this is the official abbreviation of the project.

**Comment by annakijas1** [comment]
@bwbohl if you want to update the text for that page please go ahead. I was trying to use the project descriptions that I found on the project sites, but since you are closer to the project it would be great if you can provide the description.

**Pull request merged**
