### PR TITLE
Feat(projects): add Furnace and Fugue project

### PR DESCRIPTION
**Pull request by musicEnfanthen**
This PR adds the Furnace and Fugue project to the projects subpage. Text provided and confirmed by the project editors.

### CODE REVIEW

**Comment by annakijas1** [comment]
Ready to be published.

**Review by annakijas1 — APPROVED** [review]
Ready for publication.

**Comment by musicEnfanthen** [comment]
Thank you @annakijas1 . @rettinghaus do you want to merge?

**Comment by musicEnfanthen** [comment]
Thank you!

**Pull request merged**
