### PR TITLE
Little refactorings for tutorial.js

### LINKED ISSUE #138: Error message for renderings in tutorials is misleading
As mentioned by @KristinaRichts and @krHERO , the current error message when an encoding cannot be rendered in the tutorials can be misleading ("Please adjust your encoding …"). 

Especially for metadata tutorials and use cases, the encoding will obviously not be rendered most of the time, what is correct for those cases. The displayed message  should not give the impression that there is a mistake that should be adjusted.

### PR DESCRIPTION
**Pull request by musicEnfanthen**
This PR proposes some light refactorings for tutorials.js, including

- handling of step number incrementation
- removing redundant calls and simplifying functions
- improving messages ( fixes #138 ) and 
- refactoring variable names for consistency 

It also adds another log if a stepNumber is thrown with a value of NaN to improve debugging of #136 .

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
@KristinaRichts @krHERO
Could you have a look if you are fine with the changes in https://github.com/music-encoding/music-encoding.github.io/pull/139/commits/9333d9ee431521a1b5d6a70ba6510a9b578d7fe7 ?

**Comment by bwbohl** [comment]
@KristinaRichts and @krHERO any chance you have a look at this?

**Comment by KristinaRichts** [comment]
I also think, that the error message you suggested is better than the previous one, but in the long run, the reactions should be so clear that the user can understand why the coding cannot be rendered.

**Comment by bwbohl** [comment]
thx @krHERO and @KristinaRichts merged for now and noted for future improvement in #150

**Pull request merged**
