### PR TITLE
Tutorials: Refactor 100 Structure Tutorial

### LINKED ISSUE #68: Clean up 100_structure tutorial
There are a few little missing bits on the Quickstart tutorial:

https://music-encoding.org/tutorials/100-structure.html

"Not ready yet" and "TODO: e.g., Link to XML Introduction"

These should be tidied up.

### PR DESCRIPTION
**Pull request by musicEnfanthen**
This PR adapts the 100 structure tutorial to the new framework (removing preview snippets, adjusting css classes, move steps to subfolders etc.) and drives it forward to function as a basic introduction to XML principles and the minimum structure for a valid MEI document (as it was proposed by @margrethesb ).

Final state at the end of the tutorial:
```
<mei xmlns="http://www.music-encoding.org/ns/mei">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title></title>
            </titleStmt>
            <pubStmt></pubStmt>
        </fileDesc>
    </meiHead>
    <music></music>
</mei>
```

Tried another way of title to be displayed in the side menu: "Basic 100: XML and MEI", to indicate the level of difficulty to the user more explicitly. But I don't mind to change this back if necessary.

Should we rename the files of this tutorial, too? At the moment it is all 100_structure_XXX.

Finally, this fixes #68 by providing the requested clean up.

### CODE REVIEW

**Comment by ahankinson** [comment]
In the American University system, '101' pre-dates Orwell to refer to any introductory course: https://en.wikipedia.org/wiki/101_(topic)

**Comment by kepper** [comment]
I remembered that from high school when we spoke abot Orwell, but I didn't find a reference to that right away. Thanks :-)

**Comment by ahankinson** [comment]
The 101 in 1984 is a different thing. It's named after a conference room (Room 101) at the BBC, where Orwell had to attend really tedious meetings when he worked there. They made a [plaster cast](http://news.bbc.co.uk/1/hi/entertainment/3267261.stm) of it before it was renovated away.

**Comment by kepper** [comment]
Yes, finding that information made me doubt my memories. But at least in my english class (it could have been german – I don't recall anymore) the teacher's statement was that the 101 referred to the introductory course, to which Winston was sent back to learn the basics. From my perspective, both explanations make sense – but I really prefer the American University System explanation for our MEI tutorials ;-)

**Comment by musicEnfanthen** [comment]
Thanks a lot, also for the insights in American University systems and literature history :)

>  I wouldn't put these numbers on dislay, 

Removed it and changed the name to display: "XML basics and minimal MEI structure"

> and I wouldn't repeat the label "Quickstart". 

Where do you see this? It was in the old version, but I thought I removed it completely. Did I miss something?

> With "structure", I would already expect more than the current content. 

Agree. So I would rename all the files to 100_minimal_structure.XXX. That's ok with you?

Are there any other requested changes that I have overlooked between love, peace, plenty and truth? ;)

**Comment by musicEnfanthen** [comment]
Just recognized that I missed some links and the desc of pubStmt in step 4. Added them in the latest commits.

Doing so, I ran into the guidelines' [Minimal Header Information](https://music-encoding.org/guidelines/v4/content/metadata.html#headerMinimalRecommendedHeader) section: 

> Within the pubStmt, a publisher, distributor, or other agency responsible for the file is required.

Is this correct? The ODD file of [pubStmt](https://music-encoding.org/guidelines/v4/elements/pubstmt.html) lists only contents with "optional" or "zeroOrMore" declarations.

**Comment by musicEnfanthen** [comment]
Thanks a lot!

**Pull request merged**
