### PR TITLE
Added post for workshop registration

### PR DESCRIPTION
**Pull request by CliffordAnderson**
...schedule will follow shortly in another post. Thanks!

### CODE REVIEW

**Comment by kepper** [comment]
Hi Cliff, sorry for not pulling in your PR yet. I changed emails with Joy and suggested to set up a dedicated email address "workshop2019@music-encoding.org" which I would then forward to you, Joy and myself, so that people in charge will receive it. Could you update the PR accordingly? I also think that we're so close to the weekend that people won't be receptive to the annoucement anymore. Wouldn't it make more sense to get this out first thing on Monday?

**Comment by CliffordAnderson** [comment]
Hi Jo, Thanks for our conversation just now. I've updated the email address and release date for Tuesday. After we reach final consensus on the schedule, I'll add that information to the post too. Thanks!

**Comment by kepper** [comment]
Hi Cliff, Thanks from my side as well! I just set up the mail address, but that requires Joy and you to confirm that you're willing to receive from there – you should have something in your inbox. Maybe you want to double-check your spam folder, just in case…

**Comment by CliffordAnderson** [comment]
Thanks, Jo. I confirmed the email. I also checked with Joy and we are happy with the tentative schedule. As you see, I've added it to the post. If all looks good to you, I think the pull request is ready.

**Comment by kepper** [comment]
thank you very much!

**Pull request merged**
