### PR TITLE
Add 2024 Call for Nominations

### PR DESCRIPTION
**Pull request by musicog**
This PR adds the Call for Nominations for the 2024 MEI election to the news page
Currently a draft PR to prevent accidental merging until Oct 25, 2024 (start of nominations phase)

### CODE REVIEW

**Review by peterstadler — APPROVED** [review]
Looks good to me, many thanks!

**Comment by musicEnfanthen** [comment]
@musicog Is this good to go?

**Comment by peterstadler** [comment]
That should be posted today but @musicog should have another look since I just modified the dates

**Comment by musicog** [comment]
Thanks @peterstadler @musicEnfanthen, and sorry for the delay - time got away from me on Friday and I didn't want to send the notification late at night / over the weekend. This is now ready for merging!

**Pull request merged**
