### PR TITLE
Created conference landing page

### PR DESCRIPTION
**Pull request by annakijas1**
Please review - pulled in image from the TEI conference page (check to see if this will work)

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
Thank you @annakijas1 . Will check it in a minute.

**Comment by musicEnfanthen** [comment]
Looks great, thank you @annakijas1 . Just added some commits to activate the page in the website menu and to fix some structured data.

**Comment by musicEnfanthen** [comment]
Ready to be re-reviewed and merged if OK.

**Review by rettinghaus — APPROVED** [review]
Thanks! Looks good to me.

**Pull request merged**
