### PR TITLE
remove lock file for running locally

### PR DESCRIPTION
**Pull request by rettinghaus**
This removes the `Gemfile.lock` making it easier to develop locally. 
If I'm not mistaken we don't have dependencies there for running it on GitHub.

### CODE REVIEW

**Comment by bwbohl** [comment]
@rettinghaus can you give me a head's start on this?

**Comment by rettinghaus** [comment]
The Gemfile.lock tells Bundler which dependencies should be used instead of resolving dependencies. This may cause trouble on local machines. Gets regenerated on `bundle install`.

**Comment by rettinghaus** [comment]
this is still waiting …
If we want to have as many people as possible to contribute, we should make testing easier.

**Comment by kepper** [comment]
I plan to propose some drastic changes to our setup, which should also simplify testing. Basically, I think the separation of Guidelines and Specs into two repos is a nightmare. Putting the CSS in a third repo surely doesn't help on that. In essence, I'd like to go back to ODD, or at least ORD (One Repo does-it-all). Let's bring this up on Friday at MEC2020, and then decide how to proceed…

**Comment by bwbohl** [comment]
> I plan to propose some drastic changes to our setup, which should also simplify testing. Basically, I think the separation of Guidelines and Specs into two repos is a nightmare. Putting the CSS in a third repo surely doesn't help on that. In essence, I'd like to go back to ODD, or at least ORD (One Repo does-it-all). Let's bring this up on Friday at MEC2020, and then decide how to proceed…

As the planned changes are not connected to the website pages I think we could go on with this, right?

**Comment by bwbohl** [comment]
I did some research and I would suggest to keep the lock file, see: https://bundler.io/rationale.html#checking-your-code-into-version-control

**Comment by rettinghaus** [comment]
After dependabot annoyed us again, I want to re-propose removing `Gemfile.lock` as it can result in difficulties for local tests and GitHub pages uses it's own strict dependencies. See https://ben.balter.com/jekyll-style-guide/gitignore/

I made an update with d439b8d1f6b6c2973b647bbb36714d562ee33908 but we shouldn't need to keep track of this.

**Pull request closed without merging**
