### PR TITLE
Removing broken links to acm.org

### PR DESCRIPTION
**Pull request by rettinghaus**
This removes links to pdf files behind paywalls. Also one doubled doi link is removed.

### CODE REVIEW

**Comment by ahankinson** [comment]
I would prefer to instead see a note indicating pay wall status, and/or an alternate copy linked on the theory that a restricted link is still better than none at all.

**Comment by rettinghaus** [comment]
@ahankinson There is still the DOI, that leeds to the download page. 
BTW the dropbox link to your Ph.D. Thesis is broken, too.

**Comment by pe-ro** [comment]
I agree with @ahankinson -- I'd rather see a notification of the pay wall than not see the link at all.

**Comment by rettinghaus** [comment]
Am I talking chinese? The links are broken and just return an error: 
http://delivery.acm.org/10.1145/2980000/2970053/p33-bell.pdf
There is no notification of any sort. 
The DOI instead directs to the article page with the download link: 
https://dl.acm.org/citation.cfm?doid=2970044.2970053
I really don't see the point in keeping broken links, sorry.

**Comment by pe-ro** [comment]
You're right -- keeping broken links serves no purpose.  But where are the broken links coming from?

The entry for the item in the original, hand-coded bibliography was
```
Bell, Eamonn and Laurent Pugin. "Approaches to Handwritten Conductor Annotation 
Extraction in Musical Scores." DLfM 2016: Proceedings of the 3rd International workshop 
on Digital Libraries for Musicology. New York: Association for Computing Machinery, 
2016. 33-36. <http://dx.doi.org/10.1145/2970044.2970053>.
```
so what's creating the `http://delivery.acm.org/10.1145/2980000/2970053/p33-bell.pdf` link?

Also, there appear to be a number of items missing from the dynamically generated bibliography compared with the original.  For example --
```
Bohl, Benjamin, Johannes Kepper and Röwenstrunk Daniel. "Perspektiven digitaler 
Musikeditionen aus der Sicht des Edirom-Projekts." Die Tonkunst: Magazin für 
klassische Musik und Musikwissenschaft 5.3 (2011): 270-276.
```
is no longer present.

**Comment by rettinghaus** [comment]
@musicEnfanthen can you shed some light? And maybe add the missing items to the bibtex file?

**Comment by ahankinson** [comment]
@rettinghaus Sorry for any misunderstanding but in your PR you didn't mention the links didn't work, you just mentioned that you removed links to PDFs behind pay walls.

**Comment by musicEnfanthen** [comment]
Sorry for any trouble and inconvenience. 

The links to the DLfM article pdfs were added by me (manually) to provide direct access to the pdf in case you are not paywalled. Before my PR, I had checked the links twice and had never encountered this error message which is shown now. At least for the two Early Music articles, I can confirm that the links are working, not broken. I don't have access now to the DLfM articles, but let me check on monday if the links are really broken or "just" restricted. Nonetheless, you are absolutely right, for links that are not broken, but behind paywall, we should use the `note` field to indicate the restricted access.

@pe-ro I just double-checked the list again and can't see any items from the "hand-coded" version that are not in the dynamic one. Of course, the order of the entries has slightly changed: it is grouped by publication year now (bibbase default), not in alphabetical order. It is possible to switch the `group by` handle at the top of the list to have it sorted by year, author, or publication type. If you want the list to be sorted by author by default, one would have to add another parameter (`&group0=author`) to the url that is requesting the bibbase file.

The item that you mentioned (Bohl, Kepper & Röwenstrunk in Tonkunst 2011) is indeed missing, and it would be good to add it. It seems, that it was already missing in the original list, at least I cannot find it in the older version(s). But maybe I am looking at the wrong place. Is there another old version that I am missing?

**Comment by rettinghaus** [comment]
@ahankinson Sorry, I thought the title "Removing broken links" would have said enough ;-)

**Comment by ahankinson** [comment]
Some people consider pay walled links "broken".

**Comment by rettinghaus** [comment]
I added the "missing" article. We can re-add (working) links to pdfs later.

**Comment by musicEnfanthen** [comment]
@rettinghaus thanks for adding the missing article and catching the broken links.

Just to finish up the open ends of the discussion: 

I just checked the DLfM links again and see the issue now: The pdf links are correct indeed, but they are working ONLY AFTER going to the article page with the download link and clicking on that link. I guess, some authorization stuff is added to the cache then, and afterwards the pdf link (re)opens without any error message. Knowing this, it really makes little sense to have the links (re)added, as you have to go first to the article page anyway.

The pdf links for the two Early Music articles are working correct and one could re-add them with an appropriate note (something like: Available only by subsricption"?)

@pe-ro Thank you for the information about the less selective version of the bibliography and sharing your Word file with further literature mentioning MEI. Let's continue this in #21

**Comment by rettinghaus** [comment]
@musicEnfanthen is there a good way to provide the needed note to the pdf links? Personally I would say the DOI is enough as the article is just another click away. It's just a little less convenient for people *with* subscription.

**Comment by ahankinson** [comment]
As this PR was closed before being fully resolved, how should we proceed? @rettinghaus ?

**Comment by rettinghaus** [comment]
moved unsolved discussion to #23

**Pull request merged**
