### PR TITLE
Tutorials

### PR DESCRIPTION
**Pull request by ahankinson**
This is an administrative PR, moving the tutorials into the master branch. All approvals went through on PR #57 

Exceptionally, I will merge this myself, but have opened this PR to serve as a record.

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
@ahankinson thanks for your enthusiasm about the tutorials. But this was not intended to be released on `master` yet. As you see with the different issues you had to open, there is still a lot of work and clean up to do. The time will come to transfer everything to `master`, but for now the tutorials should only live on the `tutorials` branch.

Could you please revert this PR from `master` branch?

**Comment by ahankinson** [comment]
Yes, I can.

However, I would note that there is some value in having people kick the tyres on the live site, without having to check out and build the `tutorials` branch and run it locally. I don't think the issues that I raised are show-stoppers -- they can probably be addressed with just a few small changes.

If you still want me to revert it, I can, but I would counter-propose that we call this a 'beta' release?

**Comment by musicEnfanthen** [comment]
Completely see your point. But in the current state it would be more like an 'epsilon' release with a lot of open ends (like the structure tutorial). 

There will probably be some hard changes for the tutorial logic as well as the visual outcome as discussed in #64 and #65. Let us just finalize these most pending issues and we will be happy to get everyone kicked in.

So right now, I would still ask for a reversion from `master`. What do you think @kepper ?

PS: I have to apologize for all the confusion, as I probably did not explicitly enough point out in my LGTM-message in #57 that it should go only to `tutorials` branch.

**Comment by kepper** [comment]
very briefly – I'm also convinced that this should live under the hood for a little longer. Yes, we need to involve as many people as possible, but we don't want to confuse others, at least as long as the technology is still moving…

**Comment by ahankinson** [comment]
It has been reverted.

**Comment by ahankinson** [comment]
I think.

**Comment by musicEnfanthen** [comment]
Thank you a lot!

**Pull request merged**
