### PR TITLE
feat(tutorials): add mechanism to translate strings from js file

### PR DESCRIPTION
**Pull request by musicEnfanthen**
This PR adds a (extendable) mechanism to translate the yet untranslated strings from the tutorial's JS and HTML file. In this sense, it complements the PR #436  .

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
@martha-thomae @davidrizo Could you have a short look if the translations in https://github.com/music-encoding/music-encoding.github.io/pull/460/files#diff-077f0a162b53980ff94415c8c60525a61e2addc876b3f7a0a81c4e5fcf7fd132R51-R70 are ok?

**Review by rettinghaus — APPROVED** [review]
Looks good to me.

**Comment by martha-thomae** [comment]
Hi! I couldn't get to this until now.
I think those lines are ok. And I also ran the tutorials to see the changes. Thank you for working on this, @musicEnfanthen!

**Review by martha-thomae — APPROVED** [review]

**Comment by musicEnfanthen** [comment]
Thanks for checking, @martha-thomae !

**Pull request merged**
