### PR TITLE
Add update for the metadata working meeting

### PR DESCRIPTION
**Pull request by martha-thomae**
Post on update for metadata meeting (now to be held online), requested by Kristina Richts. Ready for merge.

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
Thanks Martha.

Could you please provide a short description for the PR and indicate if it is ready to be merged? (Sorry, I was too hasty with merging #167 .)

**Comment by martha-thomae** [comment]
Done, @musicEnfanthen. Thanks!
Sorry, I tend to omit the description when it matches the title of the PR very closely. Will do that next time. 
I think it is ready to merge. I have checked it on my own machine and it looks fine.

Thank you!

**Comment by musicEnfanthen** [comment]
Thank you 🙂

**Comment by martha-thomae** [comment]
Thank you! 😊

**Pull request merged**
