### PR TITLE
adding css for new guidelines version

### PR DESCRIPTION
**Pull request by kepper**
this goes along with the improve-spec-extraction branch on the guidelines repo

### CODE REVIEW

**Comment by ahankinson** [comment]
Should this one be merged first?

**Comment by kepper** [comment]
this one is necessary to render the other one properly, otherwise it'll look a bit awkward o-) But please check before merging – I _think_ I took care of everything, but who knows?

**Comment by ahankinson** [comment]
Looks good. I will merge. Do we need to clean up the old guidelines CSS? If so, where is it?

**Comment by kepper** [comment]
That CSS is mixed in the regular CSS. I haven't looked into that yet, but it should be cleaned, yes.

**Pull request merged**
