### PR TITLE
Create verovio.md

### PR DESCRIPTION
**Pull request by annakijas1**
Newly created project page, part of wiki cleanup.

### CODE REVIEW

**Comment by annakijas1** [comment]
What if instead of including Verovio (and MEICO) on the Project page we let it be on the Tools page, but create a tools.md page that appears on the project page and has a general text about tools/software/apps and points to the Tools page? This way it can still be found easily from the Project page?

**Comment by musicEnfanthen** [comment]
@annakijas1 Would you like to draft out such a tools.md page pointing to the tools section?

**Comment by annakijas1** [comment]
@musicEnfanthen would the tools.md page appear in the list of projects or or would it be one of the tabs after "active," "archived"?

**Comment by musicEnfanthen** [comment]
@annakijas1 Another tab seems like an overkill. 

Maybe it would be totally sufficient to include a short statement at the very top of the page that says something like: for tools look there... ?

**Comment by annakijas1** [comment]
@musicEnfanthen yes, I think that might be a better solution.

**Pull request closed without merging**
