### PR TITLE
MEC2024: added program details

### PR DESCRIPTION
**Pull request by annakijas1**
@musicEnfanthen or @bwbohl  I updated the conference program with the schedule. Please review and merge if there are no issues.

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
@bwbohl Ready to merge from my side.

**Comment by musicEnfanthen** [comment]
Sorry, had to run this through a linter (prettier) so it is easier to read and maintain now.

**Comment by musicEnfanthen** [comment]
@rettinghaus May I ask you to merge?

**Review by rettinghaus — APPROVED** [review]

**Comment by rettinghaus** [comment]
@musicEnfanthen I wasn't assigned! 😉

**Pull request merged**
