### PR TITLE
Tutorials: Adapt new framework to 102 March Tutorial

### PR DESCRIPTION
**Pull request by musicEnfanthen**
This PR adjusts the 102 March tutorial to the new rewritten framework. It removes all mentionings of the former preview sections in the desc and xml files, adjusted all xml snippets and prefill files, and added the responsibility declarations in a new end file. Additionally, it tries to enhance the accessibility of the tutorial a little bit more (esp. for untrained people) in providing more guidance and more basic explanations in the single tutorial steps.

Ready to review.

### CODE REVIEW

**Comment by musicEnfanthen** [comment]
@margrethesb Thanks for going through. Fixed your reqested changes.

**Comment by musicEnfanthen** [comment]
> **short in given time** "the"?

Is this at the same place like the one above it in step 5?

**Comment by margrethesb** [comment]
> > **short in given time** "the"?
> 
> Is this at the same place like the one above it in step 5?

Ehm, I forgot to refer to where it is, now I can't find it... Sorry! I'll keep looking.

**Comment by margrethesb** [comment]
> @margrethesb Thanks for going through. Fixed your reqested changes.

Not quite done yet...

**Comment by musicEnfanthen** [comment]
NB for further changes: If you are on "Files changed" and then click a little bit right of the line numbers of any file, there will be a little blue "+" sign that allows you to make comments directly to any specific line. This should make it  easier for you to address and locate the position of a requested change.

**Comment by margrethesb** [comment]
> NB for further changes: If you are on "Files changed" and then click a little bit right of the line numbers of any file, there will be a little blue "+" sign that allows you to make comments directly to any specific line. This should make it easier for you to address and locate the position of a requested change.

Yep, finally saw that I wouldn't make any crises by doing that. Sorry!

**Comment by musicEnfanthen** [comment]
> Yep, finally saw that I wouldn't make any crises by doing that. Sorry!

No problem at all :) Thanks a lot for your review! Will address your requests right now.

**Comment by musicEnfanthen** [comment]
> Step 11:
> 
> **These verbal instructions** Verbal?

This is borrowed from the guidelines: https://music-encoding.org/guidelines/v4/content/cmn.html#cmnDynam

> Common Music Notation provides two different methodologies for expressing the volume of a note, phrase, section, etc. The first is a verbal instruction providing such information in human language, possibly in an abbreviated form. An example is the word piano, indicating a quiet volume, often abbreviated as p. In MEI, verbal instructions like this are encoded using the dynam element from the Shared module

Changed to: These are placed …

**Comment by musicEnfanthen** [comment]
> Step 12:
> 
> line 420: "...**The** note element"

Guess that it is in the .json file on line 420?

> line 11: **...as child elements of the** of the what?

of the corresponding events

**Comment by musicEnfanthen** [comment]
Hope, I have catched them all. 

If you are fine, feel free to merge :)

**Pull request merged**
